language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aalmeida/react-test -f ./client/Dockerfile.dev ./client
# - docker build myOtherProject...

script:
  - docker run -e CI=true aalmeida/react-test npm test
# - run my other project test

after_success:
  - docker build -t aalmeida/multi-client ./client
  - docker build -t aalmeida/multi-nginx ./nginx
  - docker build -t aalmeida/multi-server ./server
  - docker build -t aalmeida/multi-worker ./worker
  # push to docker hub
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin 
