language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aalmeida88/react-test -f ./client/Dockerfile.dev ./client
# - docker build myOtherProject...

script:
  - docker run -e CI=true aalmeida88/react-test npm test
# - run my other project test

after_success:
  - docker build -t aalmeida88/multi-client ./client
  - docker build -t aalmeida88/multi-nginx ./nginx
  - docker build -t aalmeida88/multi-server ./server
  - docker build -t aalmeida88/multi-worker ./worker
  # login to docker-hub
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin 
  # push to docker hub
  - docker push aalmeida88/multi-client
  - docker push aalmeida88/multi-nginx
  - docker push aalmeida88/multi-server
  - docker push aalmeida88/multi-worker 