language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aalmeida88/react-test -f ./client/Dockerfile.dev ./client
# - docker build myOtherProject...

script:
  - docker run -e CI=true aalmeida88/react-test npm test
# - run my other project test

after_success:
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-nginx ./nginx
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker
  # login to docker-hub
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin 
  # push to docker hub
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-591344712656"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"